Drop support for Elixir versions < 1.11
Ecto stopped supporting them in v3.11 so this package should follow
its lead.

https://github.com/elixir-ecto/ecto/pull/4212

==> ecto
warning: the dependency :ecto requires Elixir "~> 1.11" but you are running on v1.10.4
Compiling 56 files (.ex)

== Compilation error in file lib/ecto/repo/preloader.ex ==
** (CompileError) lib/ecto/repo/preloader.ex:362: cannot find or invoke local is_struct/2 inside guard. Only macros can be invoked in a guard and they must be defined before their invocation. Called as: is_struct(field, DynamicExpr)
    (stdlib 3.12.1.2) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.12.1.2) lists.erl:1355: :lists.mapfoldl/3
    (elixir 1.10.4) expanding macro: Kernel.or/2
    lib/ecto/repo/preloader.ex:362: Ecto.Repo.Preloader.add_preload_order/2
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"